export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_LOGOUT = "USER_LOGOUT" 

export const USER_UBDATE_SUCCESS = "USER_UBDATE_SUCCESS" 
export const USER_UBDATE_REQUEST = "USER_UBDATE_REQUEST" 
export const USER_UBDATE_FAIL = "USER_UBDATE_FAIL" 
export const USER_UBDATE_RESET = "USER_UBDATE_RESET" 

export const USER_GET_PROFILE_SUCCESS = "USER_GET_PROFILE_SUCCESS" 
export const USER_GET_PROFILE_REQUEST = "USER_GET_PROFILE_REQUEST" 
export const USER_GET_PROFILE_FAIL = "USER_GET_PROFILE_FAIL" 

